### ISSUE TITLE
Python Code Needed

### ISSUE THREAD

**Issue by codeiyapa** [codeiyapa/Hactober-Fest-Special#4]
- [ ] Create Python Folder if not already there.
- [ ] Add codes that are useful and others can also learn from that code.
- [ ] Don't spam PR
- [ ] Follow the Hacktober Fest community guidelines

**Comment by naresh-kumar-babu** [comment]
Hey, Can I work on this issue under Hacktoberfest'21?

**Comment by codeiyapa** [comment]
> Hey, Can I work on this issue under Hacktoberfest'21?

Yes go ahead

**Comment by Ridhikalra** [comment]
Hey, please assign this issue to me.

**Comment by anurag629** [comment]
I want to contribute.
Assign me also
